#!/usr/bin/env python3
"""hmi_codegen.py — generate the PLC-side HMI interface layer from the
approved (or draft) RD11/RD08 tables: the professional 3-layer pattern.

  DB_HMI.scl     one interface DB — the ONLY area an HMI may write:
                 Cmd (buttons/selectors), Set (numeric setpoints,
                 min/max from RD11), Sts (indicators, PLC-written).
  DB_Alarm.scl   one Bool per RD08 alarm (ISA-18.2 texts as comments) —
                 the HMI's discrete-alarm mechanism subscribes here.
  hmi_tags.xlsx  tag import sheet for the HMI engineer (TIA import).
  HMI_WIRING_PROPOSAL.md  suggested FB-input bindings. Wiring changes
                 program semantics, so the proposal is NEVER auto-applied
                 — the engineer approves each line (human-in-the-loop).

Reads only the RD tables; invents nothing. Rows it cannot parse are
reported, not silently dropped.
"""

from __future__ import annotations

import re
from pathlib import Path

_ROW_RE = re.compile(r"^\|(.+)\|\s*$")


def _table_rows(md_text: str, header_key: str) -> list[list[str]]:
    """Cells of the pipe table whose header contains header_key."""
    rows, in_table, seen_sep = [], False, False
    for line in md_text.splitlines():
        m = _ROW_RE.match(line.strip())
        if not m:
            in_table = seen_sep = False
            continue
        cells = [c.strip() for c in m.group(1).split("|")]
        if not in_table:
            if header_key in line:
                in_table, seen_sep = True, False
            continue
        if not seen_sep:
            seen_sep = True          # the |---|---| separator line
            continue
        if any(cells):
            rows.append(cells)
    return rows


def _ident(path: str) -> tuple[str, str, str]:
    """'DB_HMI.Cmd.bBtn_X' -> ('DB_HMI', 'Cmd', 'bBtn_X'); '' on mismatch."""
    parts = path.split(".")
    return tuple(parts) if len(parts) == 3 else ("", "", "")  # type: ignore


def generate_hmi_interface(project_root: Path) -> dict:
    root = Path(project_root)
    rd11 = root / "metadata" / "RD11_HMI.md"
    rd08 = root / "metadata" / "RD08_Alarm.md"
    out = root / "_output"
    out.mkdir(exist_ok=True)
    problems: list[str] = []

    if not rd11.exists():
        return {"ok": False,
                "msg": "RD11_HMI.md missing — generate the HMI draft first"}
    tag_rows = _table_rows(rd11.read_text(encoding="utf-8"), "HMI_TagID")

    cmd: list[tuple[str, str]] = []      # (member, comment)
    sts: list[tuple[str, str]] = []
    setp: list[tuple[str, str, str, str, str]] = []  # member, mn, mx, unit, cm
    wiring: list[tuple[str, str, str]] = []          # tag, legacy, direction

    for cells in tag_rows:
        if len(cells) < 12 or not cells[0]:
            continue
        (tag_id, plc_tag, _scr, _etype, _en, _tr, label_de,
         rw, mn, mx, unit, notes) = cells[:12]
        db, area, member = _ident(plc_tag)
        if db != "DB_HMI" or not member:
            problems.append(f"{tag_id}: unexpected PLC_Tag '{plc_tag}'")
            continue
        legacy = ""
        m = re.search(r"legacy\s+([A-Z]+\s?\d+(?:\.\d+)?)", notes)
        if m:
            legacy = m.group(1)
        comment = label_de or tag_id
        if area == "Cmd":
            cmd.append((member, comment))
            wiring.append((f"DB_HMI.Cmd.{member}", legacy, "HMI → PLC"))
        elif area == "Sts":
            sts.append((member, comment))
            wiring.append((f"DB_HMI.Sts.{member}", legacy, "PLC → HMI"))
        elif area == "Set":
            setp.append((member, mn or "0", mx or "999", unit, comment))
            wiring.append((f"DB_HMI.Set.{member}", legacy, "HMI → PLC"))
        else:
            problems.append(f"{tag_id}: unknown area '{area}'")

    def _struct(name: str, lines: list[str]) -> list[str]:
        if not lines:
            return []
        return [f"      {name} : STRUCT"] + lines + ["      END_STRUCT;"]

    # Mrg (merged command) members exist ONLY for wiring lines the engineer
    # explicitly approved (hmi_wiring.json): Mrg.x := physical OR Cmd.x is
    # generated by FC_HMI_Wiring; FB inputs are then re-pointed at Mrg.
    mrg: list[tuple[str, str]] = []
    try:
        from hmi_wiring import load_wiring  # type: ignore
        _wd = load_wiring(root)
        mrg = [(m, c) for m, c in cmd
               if (_wd.get(f"DB_HMI.Cmd.{m}") or {}).get("approved") is True]
    except Exception:
        pass

    db_lines: list[str] = []
    db_lines += _struct("Cmd", [
        f"         {m} : Bool;   // {c}" for m, c in cmd])
    db_lines += _struct("Set", [
        f"         {m} : Int;   // {c} [{mn}..{mx}] {u}".rstrip()
        for m, mn, mx, u, c in setp])
    db_lines += _struct("Sts", [
        f"         {m} : Bool;   // {c}" for m, c in sts])
    db_lines += _struct("Mrg", [
        f"         {m} : Bool;   // {c} — approved merge (phys OR HMI)"
        for m, c in mrg])

    db_hmi = (
        'DATA_BLOCK "DB_HMI"\n'
        "{ S7_Optimized_Access := 'TRUE' }\n"
        "VERSION : 0.1\n"
        "// HMI interface layer — the ONLY area the HMI writes (Cmd/Set).\n"
        "// Sts is PLC-written. Generated from RD11_HMI.md — regenerate\n"
        "// after RD11 changes; do not edit by hand.\n"
        "   STRUCT\n" + "\n".join(db_lines) + "\n   END_STRUCT;\n"
        "BEGIN\nEND_DATA_BLOCK;\n")
    (out / "DB_HMI.scl").write_text(db_hmi, encoding="utf-8")

    files = ["DB_HMI.scl"]
    alarms: list[list[str]] = []
    if rd08.exists():
        alarms = [c for c in _table_rows(
            rd08.read_text(encoding="utf-8"), "AlarmID") if c and c[0]]
        alm_lines = []
        for cells in alarms:
            if len(cells) < 11:
                continue
            alarm_id, alarm_name, cls = cells[0], cells[1], cells[2]
            text_de = cells[10] or cells[8]
            alm_lines.append(f"      {alarm_id}_{alarm_name} : Bool;"
                             f"   // [{cls}] {text_de}")
        db_alarm = (
            'DATA_BLOCK "DB_Alarm"\n'
            "{ S7_Optimized_Access := 'TRUE' }\n"
            "VERSION : 0.1\n"
            "// One Bool per RD08 alarm — the HMI discrete-alarm list\n"
            "// subscribes here (ISA-18.2). Generated from RD08_Alarm.md.\n"
            "   STRUCT\n" + "\n".join(alm_lines) + "\n   END_STRUCT;\n"
            "BEGIN\nEND_DATA_BLOCK;\n")
        (out / "DB_Alarm.scl").write_text(db_alarm, encoding="utf-8")
        files.append("DB_Alarm.scl")

    # wiring proposal — engineer approves; nothing is auto-bound
    wp = ["# HMI wiring proposal — NOT auto-applied", "",
          "Binding an HMI command into an FB input changes program",
          "semantics (e.g. OR-ing a physical pushbutton with an HMI",
          "button). Every line below needs the engineer's decision at",
          "Gate 3; code generation then uses the approved bindings.", "",
          "| Interface tag | Legacy pulpit signal | Direction | Suggested binding |",
          "|---------------|----------------------|-----------|-------------------|"]
    for tag, legacy, direction in wiring:
        if direction == "HMI → PLC":
            hint = (f"FB input alongside physical `{legacy}` (OR — engineer "
                    "decision)" if legacy else "FB command input")
        else:
            hint = (f"replaces lamp output `{legacy}` — drive from the FB "
                    "status" if legacy else "FB status output")
        wp.append(f"| `{tag}` | {legacy or '—'} | {direction} | {hint} |")
    if problems:
        wp += ["", "## Rows not converted (review)", ""] + \
              [f"- {p}" for p in problems]
    (out / "HMI_WIRING_PROPOSAL.md").write_text(
        "\n".join(wp) + "\n", encoding="utf-8")
    files.append("HMI_WIRING_PROPOSAL.md")

    # tag import sheet
    try:
        import openpyxl
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "HMI_Tags"
        ws.append(["Tag", "PLC path", "DataType", "Access", "Comment (DE)",
                   "Min", "Max", "Unit"])
        for m, c in cmd:
            ws.append([m, f"DB_HMI.Cmd.{m}", "Bool", "Write", c, "", "", ""])
        for m, mn, mx, u, c in setp:
            ws.append([m, f"DB_HMI.Set.{m}", "Int", "Write", c, mn, mx, u])
        for m, c in sts:
            ws.append([m, f"DB_HMI.Sts.{m}", "Bool", "Read", c, "", "", ""])
        for cells in alarms:
            if len(cells) >= 11:
                ws.append([f"{cells[0]}_{cells[1]}",
                           f"DB_Alarm.{cells[0]}_{cells[1]}", "Bool",
                           "Read", cells[10] or cells[8], "", "", ""])
        wb.save(out / "hmi_tags.xlsx")
        files.append("hmi_tags.xlsx")
    except ImportError:
        problems.append("openpyxl missing — hmi_tags.xlsx skipped")

    return {"ok": True, "files": files, "problems": problems,
            "counts": {"cmd": len(cmd), "set": len(setp), "sts": len(sts),
                       "alarms": len(alarms)}}


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("usage: hmi_codegen.py <project_root>")
        raise SystemExit(2)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(errors="replace")
    print(generate_hmi_interface(Path(sys.argv[1])))
