#!/usr/bin/env python3
"""
protocol_i18n.py — key-based string table for protocol/document generators
(FAT/SAT protocols, SISTEMA prep list, CE assessment, customer-facing docs).

Languages: DE (default — customer base is Germany), EN, TR.

Contract:
- Missing language for a key  → EN fallback + warnings.warn (loud, never a
  silent empty string).
- Missing key entirely        → ProtocolI18nKeyError (loud failure; a typo in
  a key must never produce an empty cell in a customer document).

Usage:
    from protocol_i18n import t, DEFAULT_LANG, SUPPORTED_LANGS, normalize_lang
    t("sec.io_validation", "de")          -> "1. IO-Validierungstests" (no
                                             numbering — section numbers are
                                             the generator's responsibility)
    t("common.date", "tr")                -> "Tarih"
"""

from __future__ import annotations

import sys
import warnings

DEFAULT_LANG = "de"
SUPPORTED_LANGS = ("de", "en", "tr")


def force_utf8_stdout() -> None:
    """Make stdout/stderr UTF-8 for CLI use.

    The generators print DE/TR summaries (umlauts, ı/ş, emoji). On a Windows
    console the default cp1252 codec raises UnicodeEncodeError on the final
    print — AFTER the document was written — so a successful run looks like a
    crash. Call this at the top of every CLI main(). Best-effort; no-op where
    reconfigure is unavailable.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
        except Exception:
            pass


class ProtocolI18nKeyError(KeyError):
    """Raised when a string key does not exist in the table at all."""


def normalize_lang(lang: str | None) -> str:
    """Return a supported language code; raise ValueError for unknown ones.

    Fail-loud: an unsupported language must never silently fall back —
    the caller (CLI/GUI) validates user input through this function.
    """
    code = (lang or DEFAULT_LANG).strip().lower()
    if code not in SUPPORTED_LANGS:
        raise ValueError(
            f"Unsupported protocol language {lang!r} — supported: "
            f"{', '.join(SUPPORTED_LANGS)}"
        )
    return code


def t(key: str, lang: str = DEFAULT_LANG, **fmt) -> str:
    """Translate *key* into *lang* (EN fallback with a loud warning)."""
    entry = STRINGS.get(key)
    if entry is None:
        raise ProtocolI18nKeyError(
            f"protocol_i18n: unknown string key {key!r} — the key table and "
            "the generator are out of sync."
        )
    text = entry.get(lang)
    if text is None:
        text = entry.get("en")
        if text is None:
            raise ProtocolI18nKeyError(
                f"protocol_i18n: key {key!r} has neither {lang!r} nor 'en' "
                "translation."
            )
        warnings.warn(
            f"protocol_i18n: key {key!r} missing {lang!r} translation — "
            "using EN fallback.",
            stacklevel=2,
        )
    if fmt:
        text = text.format(**fmt)
    return text


# ───────────────────────────────────────────────────────────────────────────
# String table.  Keys are namespaced:
#   common.*      document-level labels shared by all generators
#   col.*         table column headers
#   sec.*         section titles (FAT + SAT)
#   intro.*       section intro lines (blockquotes)
#   fat.*         FAT-specific row content
#   sat.*         SAT-specific row content
#   ref.*         standard reference labels (IEC/ISO/EN)
#   status.*      status words (pending boxes etc.)
# ───────────────────────────────────────────────────────────────────────────

STRINGS: dict[str, dict[str, str]] = {

    # ── common document labels ────────────────────────────────────────────
    "common.fat_title": {
        "de": "FAT-Testprotokoll (Werksabnahme)",
        "en": "FAT Test Protocol (Factory Acceptance Test)",
        "tr": "FAT Test Protokolü (Fabrika Kabul Testi)",
    },
    "common.sat_title": {
        "de": "SAT-Testprotokoll (Standortabnahme)",
        "en": "SAT Test Protocol (Site Acceptance Test)",
        "tr": "SAT Test Protokolü (Saha Kabul Testi)",
    },
    "common.project": {
        "de": "Projekt", "en": "Project", "tr": "Proje",
    },
    "common.date": {
        "de": "Datum", "en": "Date", "tr": "Tarih",
    },
    "common.platform": {
        "de": "Plattform", "en": "Platform", "tr": "Platform",
    },
    "common.tested_by": {
        "de": "Geprüft von", "en": "Tested by", "tr": "Test eden",
    },
    "common.facility": {
        "de": "Werk / Anlage", "en": "Facility", "tr": "Tesis",
    },
    "common.auto_generated": {
        "de": "Dieses Protokoll wurde automatisch von AUTOMATION FACTORY erstellt.",
        "en": "This protocol was automatically generated by AUTOMATION FACTORY.",
        "tr": "Bu protokol AUTOMATION FACTORY tarafından otomatik üretilmiştir.",
    },
    "common.fill_during_test": {
        "de": "Die Spalten „Ist-Wert“ und „Ergebnis“ sind während der Prüfung auszufüllen.",
        "en": "The \"Actual\" and \"Result\" columns must be filled in during testing.",
        "tr": "\"Gerçekleşen\" ve \"Sonuç\" kolonları test sırasında doldurulmalıdır.",
    },
    "common.safety_supervision": {
        "de": "Sicherheitsbezogene Prüfungen sind unter Aufsicht eines qualifizierten "
              "Sicherheitsingenieurs durchzuführen.",
        "en": "Safety-related tests must be performed under supervision of a "
              "qualified safety engineer.",
        "tr": "Güvenlikle ilgili testler yetkili bir güvenlik mühendisi "
              "gözetiminde yapılmalıdır.",
    },
    "common.engineer_additions": {
        "de": "Projektspezifische zusätzliche Prüfpunkte sind durch einen "
              "autorisierten Ingenieur zu ergänzen.",
        "en": "Project-specific additional test items must be added by an "
              "authorized engineer.",
        "tr": "Projeye özgü ek test maddeleri yetkili bir mühendis tarafından "
              "eklenmelidir.",
    },
    "common.signatures": {
        "de": "Testergebnis und Unterschriften",
        "en": "Test Result and Signatures",
        "tr": "Test Sonucu ve İmzalar",
    },
    "common.general_observations": {
        "de": "Allgemeine Beobachtungen",
        "en": "General Observations",
        "tr": "Genel Gözlemler",
    },
    "common.general_observations_hint": {
        "de": "_(Wichtige Beobachtungen während der Prüfung werden hier notiert.)_",
        "en": "_(Important points observed during testing are written here.)_",
        "tr": "_(Test sırasında gözlemlenen önemli noktalar buraya yazılır.)_",
    },
    "common.total_tests": {
        "de": "Gesamtzahl der Prüfungen",
        "en": "Total test count",
        "tr": "Toplam test sayısı",
    },
    "common.passed": {
        "de": "Bestanden", "en": "Passed", "tr": "Geçen",
    },
    "common.remaining": {
        "de": "Offen", "en": "Remaining", "tr": "Kalan",
    },
    "common.remaining_note": {
        "de": "Anmerkung zu offenen Prüfungen",
        "en": "Remaining test note",
        "tr": "Kalan test notu",
    },
    "common.manufacturer_rep": {
        "de": "Vertreter Hersteller",
        "en": "Manufacturer Representative",
        "tr": "Üretici Temsilcisi",
    },
    "common.customer_rep": {
        "de": "Vertreter Kunde",
        "en": "Customer Representative",
        "tr": "Müşteri Temsilcisi",
    },
    "common.tuv_rep": {
        "de": "TÜV- / CE-Vertreter",
        "en": "TÜV / CE Representative",
        "tr": "TÜV / CE Temsilcisi",
    },
    "common.test_lead": {
        "de": "Prüfleiter", "en": "Test Lead", "tr": "Test Sorumlusu",
    },
    "common.test_result": {
        "de": "Testergebnis", "en": "Test Result", "tr": "Test Sonucu",
    },
    "common.warnings": {
        "de": "Hinweise", "en": "Warnings", "tr": "Uyarılar",
    },
    "common.subject": {
        "de": "Gegenstand", "en": "Subject", "tr": "Konu",
    },
    "common.value": {
        "de": "Wert", "en": "Value", "tr": "Değer",
    },
    "common.handover_title": {
        "de": "Übergabeprotokoll",
        "en": "Handover Record",
        "tr": "Teslim Tutanağı",
    },

    # ── table columns ─────────────────────────────────────────────────────
    "col.no": {"de": "Nr.", "en": "No", "tr": "No"},
    "col.test_id": {"de": "Prüf-ID", "en": "Test ID", "tr": "Test ID"},
    "col.description": {"de": "Beschreibung", "en": "Description", "tr": "Açıklama"},
    "col.tag": {"de": "Tag", "en": "Tag", "tr": "Tag"},
    "col.type": {"de": "Typ", "en": "Type", "tr": "Tip"},
    "col.address": {"de": "Adresse", "en": "Address", "tr": "Adres"},
    "col.method": {"de": "Prüfmethode", "en": "Test Method", "tr": "Test Yöntemi"},
    "col.expected": {"de": "Soll-Ergebnis", "en": "Expected", "tr": "Beklenen"},
    "col.actual": {"de": "Ist-Wert", "en": "Actual", "tr": "Gerçekleşen"},
    "col.result": {"de": "Ergebnis", "en": "Result", "tr": "Sonuç"},
    "col.date": {"de": "Datum", "en": "Date", "tr": "Tarih"},
    "col.signature": {"de": "Unterschrift", "en": "Signature", "tr": "İmza"},
    "col.scenario": {"de": "Szenario", "en": "Scenario", "tr": "Senaryo"},
    "col.start_state": {"de": "Ausgangszustand", "en": "Start", "tr": "Başlangıç"},
    "col.action": {"de": "Aktion", "en": "Action", "tr": "Eylem"},
    "col.expected_state": {"de": "Soll-Zustand", "en": "Expected State", "tr": "Beklenen Durum"},
    "col.test_value": {"de": "Prüfwert", "en": "Test Value", "tr": "Test Değeri"},
    "col.condition": {"de": "Bedingung / Methode", "en": "Condition / Method", "tr": "Koşul / Yöntem"},
    "col.repeat": {"de": "Wdh.", "en": "Repeat", "tr": "Tekrar"},
    "col.ref": {"de": "Ref.", "en": "Ref.", "tr": "Ref."},
    "col.test": {"de": "Prüfung", "en": "Test", "tr": "Test"},

    # ── standard references (Ref. column values) ──────────────────────────
    "ref.iec62381": {"de": "IEC 62381", "en": "IEC 62381", "tr": "IEC 62381"},
    "ref.iec62061": {"de": "IEC 62061", "en": "IEC 62061", "tr": "IEC 62061"},
    "ref.iso13849_2": {"de": "ISO 13849-2", "en": "ISO 13849-2", "tr": "ISO 13849-2"},
    "ref.en60204_1": {"de": "EN 60204-1", "en": "EN 60204-1", "tr": "EN 60204-1"},
    "ref.iec62443": {"de": "IEC 62443 / NIS2", "en": "IEC 62443 / NIS2", "tr": "IEC 62443 / NIS2"},
    "ref.iec62682": {"de": "IEC 62682", "en": "IEC 62682", "tr": "IEC 62682"},
    "ref.project": {"de": "Projekt (RD05)", "en": "Project (RD05)", "tr": "Proje (RD05)"},

    # ── FAT section titles ────────────────────────────────────────────────
    "sec.io_validation": {
        "de": "IO-Validierungstests",
        "en": "IO Validation Tests",
        "tr": "IO Doğrulama Testleri",
    },
    "sec.safety": {
        "de": "Sicherheitsfunktionstests",
        "en": "Safety Function Tests",
        "tr": "Güvenlik Fonksiyon Testleri",
    },
    "sec.analog": {
        "de": "Analoge Grenzwerttests",
        "en": "Analog Boundary Value Tests",
        "tr": "Analog Sınır Değer Testleri",
    },
    "sec.state_machine": {
        "de": "Schrittketten- / Zustandsmaschinentests",
        "en": "State Machine Step Tests",
        "tr": "Durum Makinesi Adım Testleri",
    },
    "sec.stress": {
        "de": "Stress- / Stabilitätstests",
        "en": "Stress / Stability Tests",
        "tr": "Stres / Kararlılık Testleri",
    },
    "sec.plcsim": {
        "de": "PLCSim Advanced — Aufbau der Testumgebung",
        "en": "PLCSim Advanced — Test Environment Setup",
        "tr": "PLCSim Advanced — Test Ortamı Kurulumu",
    },
    "sec.precheck": {
        "de": "Vorprüfungen",
        "en": "Pre-Checks",
        "tr": "Ön Kontroller",
    },
    "sec.io_test": {
        "de": "IO-Test",
        "en": "IO Test",
        "tr": "IO Testi",
    },
    "sec.function_test": {
        "de": "Funktionstest (SCL-Bausteine)",
        "en": "Function Test (SCL Blocks)",
        "tr": "Fonksiyon Testi (SCL Blokları)",
    },
    "sec.alarm_test": {
        "de": "Alarmtest",
        "en": "Alarm Test",
        "tr": "Alarm Testi",
    },

    # ── SAT section titles (site acceptance — IEC 62381 SAT scope) ────────
    "sec.sat_loop_check": {
        "de": "Loop-Check mit realen Feldgeräten",
        "en": "Loop Check with Real Field Devices",
        "tr": "Gerçek Saha Cihazlarıyla Loop Check",
    },
    "sec.sat_motor_rotation": {
        "de": "Motordrehrichtungskontrolle",
        "en": "Motor Rotation Direction Check",
        "tr": "Motor Dönüş Yönü Kontrolü",
    },
    "sec.sat_sensor_alignment": {
        "de": "Sensor- / Schalterjustage",
        "en": "Sensor / Switch Alignment",
        "tr": "Sensör / Switch Hizalama",
    },
    "sec.sat_safety_chain": {
        "de": "Reale NOT-HALT-Kette und Schutztürkreis",
        "en": "Real E-Stop Chain and Guard Door Circuit",
        "tr": "Gerçek E-Stop Zinciri ve Kapı Devresi",
    },
    "sec.sat_drive_params": {
        "de": "Antriebsparameter-Verifikation",
        "en": "Drive Parameter Verification",
        "tr": "Sürücü Parametre Doğrulama",
    },
    "sec.sat_network_hmi": {
        "de": "Netzwerk- / HMI-Integration",
        "en": "Network / HMI Integration",
        "tr": "Ağ / HMI Entegrasyonu",
    },
    "sec.sat_backup_handover": {
        "de": "Datensicherung und Übergabe",
        "en": "Backup and Handover",
        "tr": "Yedekleme ve Teslim",
    },
    "sec.sat_cybersecurity": {
        "de": "Cybersicherheit (IEC 62443)",
        "en": "Cybersecurity (IEC 62443)",
        "tr": "Siber Güvenlik (IEC 62443)",
    },

    # ── section intros ────────────────────────────────────────────────────
    "intro.io_validation": {
        "de": "Jeder IO-Punkt wird durch Forcen in PLCSim validiert.",
        "en": "Each IO point is validated by forcing in PLCSim.",
        "tr": "Her IO noktası PLCSim'de force edilerek doğrulanır.",
    },
    "intro.safety": {
        "de": "Gemäß IEC 62061 / ISO 13849-2 (Validierung) — jede Prüfung beginnt "
              "im deaktivierten Zustand.",
        "en": "Per IEC 62061 / ISO 13849-2 (Validation) — each test starts in "
              "**disabled state**.",
        "tr": "IEC 62061 / ISO 13849-2 (Doğrulama) uyarınca — her test "
              "**devre dışı durumda** başlar.",
    },
    "intro.analog": {
        "de": "S7-1500 Vollausschlag = **27648** (nicht 32767). "
              "Überlaufbedingungen müssen geprüft werden.",
        "en": "S7-1500 full scale = **27648** (not 32767). Overflow conditions "
              "must be checked.",
        "tr": "S7-1500 tam skala = **27648** (32767 değil). Taşma koşulları "
              "kontrol edilmelidir.",
    },
    "intro.state_machine": {
        "de": "Jeder Zustandsübergang und jedes Watchdog-Timeout wird geprüft.",
        "en": "Each state transition and watchdog timeout is tested.",
        "tr": "Her durum geçişi ve watchdog timeout'u test edilir.",
    },
    "intro.stress": {
        "de": "Verhalten des Programms bei unerwarteten Eingangskombinationen. "
              "Jede Prüfung wird mindestens 3-mal wiederholt.",
        "en": "Code behavior under unexpected input combinations. Each test is "
              "repeated at least 3 times.",
        "tr": "Beklenmeyen giriş kombinasyonlarında program davranışı. Her test "
              "en az 3 kez tekrarlanır.",
    },
    "intro.sat_loop_check": {
        "de": "Jedes RD01-Signal wird vom realen Feldgerät bis zur SPS-Adresse "
              "durchgemessen (Leitungs- und Klemmenprüfung inklusive).",
        "en": "Each RD01 signal is verified end-to-end from the real field "
              "device to the PLC address (wiring and terminal check included).",
        "tr": "Her RD01 sinyali gerçek saha cihazından PLC adresine kadar uçtan "
              "uca doğrulanır (kablaj ve klemens kontrolü dahil).",
    },
    "intro.sat_motor_rotation": {
        "de": "Drehrichtung jedes Antriebs wird bei niedriger Drehzahl geprüft, "
              "bevor Lastbetrieb erfolgt.",
        "en": "Rotation direction of every drive is verified at low speed "
              "before any loaded operation.",
        "tr": "Her sürücünün dönüş yönü, yüklü çalışma öncesi düşük hızda "
              "doğrulanır.",
    },
    "intro.sat_sensor_alignment": {
        "de": "Endschalter, Initiatoren und Analogsensoren werden mechanisch "
              "justiert und elektrisch bestätigt.",
        "en": "Limit switches, proximity sensors and analog sensors are "
              "mechanically aligned and electrically confirmed.",
        "tr": "Limit switch'ler, endüktif sensörler ve analog sensörler mekanik "
              "olarak hizalanır ve elektriksel olarak doğrulanır.",
    },
    "intro.sat_safety_chain": {
        "de": "Die reale Sicherheitskette wird am physischen Gerät geprüft — "
              "nicht in der Simulation. Prüfung nach ISO 13849-2 (Validierung).",
        "en": "The real safety chain is tested on the physical machine — not in "
              "simulation. Validation per ISO 13849-2.",
        "tr": "Gerçek güvenlik zinciri fiziksel makinede test edilir — "
              "simülasyonda değil. ISO 13849-2 (Doğrulama) uyarınca.",
    },
    "intro.sat_drive_params": {
        "de": "Antriebsparameter (Rampen, Grenzwerte, Schutzfunktionen) werden "
              "gegen die Projektierungsunterlagen verifiziert.",
        "en": "Drive parameters (ramps, limits, protection functions) are "
              "verified against the engineering documentation.",
        "tr": "Sürücü parametreleri (rampalar, limitler, koruma fonksiyonları) "
              "proje dokümantasyonuna karşı doğrulanır.",
    },
    "intro.sat_network_hmi": {
        "de": "PROFINET-Topologie, HMI-Verbindung und Anzeigen werden im realen "
              "Anlagennetz geprüft.",
        "en": "PROFINET topology, HMI connection and displays are verified on "
              "the real plant network.",
        "tr": "PROFINET topolojisi, HMI bağlantısı ve göstergeler gerçek tesis "
              "ağında doğrulanır.",
    },
    "intro.sat_backup_handover": {
        "de": "Vor der Übergabe: vollständige Datensicherung, Wiederherstellungs"
              "test und dokumentierte Übergabe an den Betreiber.",
        "en": "Before handover: complete backup, restore test and documented "
              "handover to the operator.",
        "tr": "Teslimden önce: tam yedekleme, geri-yükleme testi ve işletmeciye "
              "dokümante teslim.",
    },
    "intro.sat_cybersecurity": {
        "de": "Grundlegende Cybersicherheits-Härtung gemäß IEC 62443 / NIS2 — "
              "Nachweis vor Inbetriebnahmeende.",
        "en": "Basic cybersecurity hardening per IEC 62443 / NIS2 — evidence "
              "required before commissioning ends.",
        "tr": "IEC 62443 / NIS2 uyarınca temel siber güvenlik sıkılaştırması — "
              "devreye alma bitmeden kanıt gerekir.",
    },

    # ── FAT: IO test methods / expected per signal type ───────────────────
    "fat.io.method.DI": {
        "de": "In PLCSim auf TRUE forcen",
        "en": "Force TRUE in PLCSim",
        "tr": "PLCSim'de TRUE'ya force et",
    },
    "fat.io.method.DQ": {
        "de": "Befehl in SCL senden, an der Klemme messen",
        "en": "Send command in SCL, measure at terminal",
        "tr": "SCL'de komut gönder, klemenste ölç",
    },
    "fat.io.method.AI": {
        "de": "Wert zwischen 0 → 27648 schreiben",
        "en": "Write value between 0 → 27648",
        "tr": "0 → 27648 arası değer yaz",
    },
    "fat.io.method.AQ": {
        "de": "0 schreiben, 0 V/mA an der Klemme verifizieren",
        "en": "Write 0, verify 0 V/mA at terminal",
        "tr": "0 yaz, klemenste 0 V/mA doğrula",
    },
    "fat.io.method.default": {
        "de": "Wert ändern",
        "en": "Change value",
        "tr": "Değeri değiştir",
    },
    "fat.io.expected.DI": {
        "de": "Zugehörige DB-Variable wird TRUE",
        "en": "Related DB variable becomes TRUE",
        "tr": "İlgili DB değişkeni TRUE olur",
    },
    "fat.io.expected.DQ": {
        "de": "Schütz / Ventil zieht an",
        "en": "Contactor / valve activates",
        "tr": "Kontaktör / valf çeker",
    },
    "fat.io.expected.AI": {
        "de": "Skalierung arbeitet korrekt",
        "en": "Scaling works correctly",
        "tr": "Ölçekleme doğru çalışır",
    },
    "fat.io.expected.AQ": {
        "de": "Analogausgang wird 0 V/mA",
        "en": "Analog output becomes 0 V/mA",
        "tr": "Analog çıkış 0 V/mA olur",
    },
    "fat.io.expected.default": {
        "de": "DB-Variable wird aktualisiert",
        "en": "DB variable updates",
        "tr": "DB değişkeni güncellenir",
    },

    # ── FAT: 6 standard safety scenarios (scenario / start / action / expected)
    "fat.safety.estop.scenario": {
        "de": "Betätigung des NOT-HALT-Tasters",
        "en": "E-Stop button activation",
        "tr": "E-Stop butonuna basılması",
    },
    "fat.safety.estop.start": {
        "de": "Maschine läuft",
        "en": "Machine is running",
        "tr": "Makine çalışıyor",
    },
    "fat.safety.estop.action": {
        "de": "NOT-HALT-Taster drücken (Öffner öffnet)",
        "en": "Press E-stop button (NC opens)",
        "tr": "E-stop butonuna bas (NC açılır)",
    },
    "fat.safety.estop.expected": {
        "de": "xSafetyOK=FALSE, alle Ausgänge abgeschaltet, iSafetyFault=1",
        "en": "xSafetyOK=FALSE, all outputs closed, iSafetyFault=1",
        "tr": "xSafetyOK=FALSE, tüm çıkışlar kapalı, iSafetyFault=1",
    },
    "fat.safety.estop_release.scenario": {
        "de": "NOT-HALT-Entriegelung — manueller Reset",
        "en": "E-Stop release — manual reset",
        "tr": "E-Stop bırakma — manuel reset",
    },
    "fat.safety.estop_release.start": {
        "de": "NOT-HALT betätigt",
        "en": "E-stop pressed",
        "tr": "E-stop basılı",
    },
    "fat.safety.estop_release.action": {
        "de": "Taster entriegeln, ohne Reset warten",
        "en": "Release button, wait without reset",
        "tr": "Butonu bırak, reset olmadan bekle",
    },
    "fat.safety.estop_release.expected": {
        "de": "Maschine darf NICHT automatisch wieder anlaufen (Reset erforderlich)",
        "en": "Machine must not restart automatically (reset required)",
        "tr": "Makine otomatik olarak yeniden BAŞLAMAMALI (reset gerekli)",
    },
    "fat.safety.door_open.scenario": {
        "de": "Öffnen der Schutztür — während des Betriebs",
        "en": "Protective door opening — during operation",
        "tr": "Koruma kapısının açılması — çalışma sırasında",
    },
    "fat.safety.door_open.start": {
        "de": "Automatikzyklus aktiv",
        "en": "Auto cycle active",
        "tr": "Otomatik çevrim aktif",
    },
    "fat.safety.door_open.action": {
        "de": "Türsensor auf FALSE forcen",
        "en": "Force door sensor to FALSE",
        "tr": "Kapı sensörünü FALSE'a force et",
    },
    "fat.safety.door_open.expected": {
        "de": "xSafetyOK=FALSE, iSafetyFault=2, kontrollierter Stopp",
        "en": "xSafetyOK=FALSE, iSafetyFault=2, controlled stop",
        "tr": "xSafetyOK=FALSE, iSafetyFault=2, kontrollü duruş",
    },
    "fat.safety.reset_ok.scenario": {
        "de": "Alle Türen geschlossen, NOT-HALT OK → Reset",
        "en": "All doors closed, E-stop OK → reset",
        "tr": "Tüm kapılar kapalı, E-stop OK → reset",
    },
    "fat.safety.reset_ok.start": {
        "de": "Fehlerzustand",
        "en": "Error state",
        "tr": "Hata durumu",
    },
    "fat.safety.reset_ok.action": {
        "de": "Alle Bedingungen OK, Reset ausführen",
        "en": "All conditions OK, issue reset",
        "tr": "Tüm koşullar OK, reset ver",
    },
    "fat.safety.reset_ok.expected": {
        "de": "Maschine kehrt nach IDLE zurück, Neustart möglich",
        "en": "Machine returns to IDLE, can be restarted",
        "tr": "Makine IDLE'a döner, yeniden başlatılabilir",
    },
    "fat.safety.channel_mismatch.scenario": {
        "de": "Kanalungleichheit Sicherheitsrelais (>100 ms)",
        "en": "Safety relay channel mismatch (>100 ms)",
        "tr": "Güvenlik rölesi kanal uyumsuzluğu (>100 ms)",
    },
    "fat.safety.channel_mismatch.start": {
        "de": "Normalbetrieb",
        "en": "Normal operation",
        "tr": "Normal çalışma",
    },
    "fat.safety.channel_mismatch.action": {
        "de": "CH1 TRUE, CH2 FALSE forcen und 150 ms warten",
        "en": "Force CH1 TRUE, CH2 FALSE and wait 150 ms",
        "tr": "CH1 TRUE, CH2 FALSE force et ve 150 ms bekle",
    },
    "fat.safety.channel_mismatch.expected": {
        "de": "iSafetyFault=10, Not-Stopp",
        "en": "iSafetyFault=10, emergency stop",
        "tr": "iSafetyFault=10, acil duruş",
    },
    "fat.safety.maintenance.scenario": {
        "de": "Wartungsmodus — Türfreigabe",
        "en": "Maintenance mode — door open permission",
        "tr": "Bakım modu — kapı açma izni",
    },
    "fat.safety.maintenance.start": {
        "de": "Wartungsmodus aktiv + Schlüssel gesteckt",
        "en": "Maintenance mode active + key installed",
        "tr": "Bakım modu aktif + anahtar takılı",
    },
    "fat.safety.maintenance.action": {
        "de": "Tür öffnen",
        "en": "Open door",
        "tr": "Kapıyı aç",
    },
    "fat.safety.maintenance.expected": {
        "de": "xSafetyOK geschützt, reduzierte Geschwindigkeit aktiv",
        "en": "xSafetyOK protected, reduced speed limit active",
        "tr": "xSafetyOK korunur, düşük hız limiti aktif",
    },
    "fat.safety.rd05_row": {
        "de": "{name} (RD05) — gemäß Projektdefinition",
        "en": "{name} (RD05) — per project definition",
        "tr": "{name} (RD05) — proje tanımına göre",
    },
    "fat.safety.rd05_from": {
        "de": "Aus RD05", "en": "From RD05", "tr": "RD05'ten",
    },

    # ── FAT: analog boundary rows (value, expectation) ────────────────────
    "fat.analog.b0": {
        "de": "Untergrenze — 0 mA / 0 V / minimaler Prozesswert",
        "en": "Lower limit — 0 mA / 0 V / minimum engineering value",
        "tr": "Alt sınır — 0 mA / 0 V / minimum mühendislik değeri",
    },
    "fat.analog.b25": {
        "de": "25 % — 4-mA-Bereich verifizieren (untere Sensorkalibrierung)",
        "en": "25% — verify 4 mA range (sensor lower calibration)",
        "tr": "%25 — 4 mA aralığını doğrula (sensör alt kalibrasyonu)",
    },
    "fat.analog.b50": {
        "de": "50 % — Mittelwertprüfung",
        "en": "50% — mid-value verification",
        "tr": "%50 — orta değer doğrulaması",
    },
    "fat.analog.b100": {
        "de": "Vollausschlag Obergrenze — maximaler Prozesswert",
        "en": "Full scale upper limit — maximum engineering value",
        "tr": "Tam skala üst sınır — maksimum mühendislik değeri",
    },
    "fat.analog.bover": {
        "de": "Überlauf +1 — begrenzt das Programm auf ≤ 27648?",
        "en": "Overflow +1 — does program clamp to ≤ 27648?",
        "tr": "Taşma +1 — program ≤ 27648'e sınırlıyor mu?",
    },
    "fat.analog.bneg": {
        "de": "Negativer Wert — begrenzt das Programm auf 0?",
        "en": "Negative value — does program clamp to 0?",
        "tr": "Negatif değer — program 0'a sınırlıyor mu?",
    },
    "fat.analog.b32767": {
        "de": "S7-300-Gewohnheit — 16-%-Fehlererkennung (falsche Formel prüfen)",
        "en": "S7-300 habit — 16% error detection (wrong formula check)",
        "tr": "S7-300 alışkanlığı — %16 hata tespiti (yanlış formül kontrolü)",
    },
    "fat.analog.no_ai_placeholder": {
        "de": "(Kein AI/AQ-Signal — RD01 prüfen)",
        "en": "(No AI/AQ signal — check RD01)",
        "tr": "(AI/AQ sinyali yok — RD01'i kontrol et)",
    },

    # ── FAT: state machine rows (test / start / action / expected) ────────
    "fat.sm.t1.test": {
        "de": "Normaler Anlauf", "en": "Normal startup", "tr": "Normal başlatma",
    },
    "fat.sm.t1.action": {
        "de": "START-Befehl geben, alle Bedingungen OK",
        "en": "Issue START command, all conditions OK",
        "tr": "START komutu ver, tüm koşullar OK",
    },
    "fat.sm.t2.test": {
        "de": "Timeout Referenzposition",
        "en": "Home position timeout",
        "tr": "Home pozisyonu timeout",
    },
    "fat.sm.t2.action": {
        "de": "Referenzschalter nie betätigen, 30 s warten",
        "en": "Never activate home switch, wait 30 s",
        "tr": "Home switch'i hiç aktive etme, 30 s bekle",
    },
    "fat.sm.t2.expected": {
        "de": "FAULT (900), Fehlercode 101",
        "en": "FAULT (900), error code 101",
        "tr": "FAULT (900), hata kodu 101",
    },
    "fat.sm.t3.test": {
        "de": "Spannbestätigung fehlt",
        "en": "Clamp confirmation missing",
        "tr": "Bağlama onayı eksik",
    },
    "fat.sm.t3.action": {
        "de": "Spannbestätigungssignal FALSE halten, 5 s warten",
        "en": "Keep clamp confirmation signal FALSE, wait 5 s",
        "tr": "Bağlama onay sinyalini FALSE tut, 5 s bekle",
    },
    "fat.sm.t3.expected": {
        "de": "FAULT (900), Fehlercode 201",
        "en": "FAULT (900), error code 201",
        "tr": "FAULT (900), hata kodu 201",
    },
    "fat.sm.t4.test": {
        "de": "NOT-HALT während der Bearbeitung",
        "en": "E-stop during processing",
        "tr": "İşleme sırasında E-stop",
    },
    "fat.sm.t4.action": {
        "de": "NOT-HALT betätigen",
        "en": "Activate E-stop",
        "tr": "E-stop'u aktive et",
    },
    "fat.sm.t4.expected": {
        "de": "EMERGENCY (999), alle Ausgänge abgeschaltet",
        "en": "EMERGENCY (999), all outputs closed",
        "tr": "EMERGENCY (999), tüm çıkışlar kapalı",
    },
    "fat.sm.t5.test": {
        "de": "STOP-Befehl im Handbetrieb",
        "en": "STOP command in manual mode",
        "tr": "Manuel modda STOP komutu",
    },
    "fat.sm.t5.action": {
        "de": "xHandModeInternal=TRUE, xStopCmd geben",
        "en": "xHandModeInternal=TRUE, issue xStopCmd",
        "tr": "xHandModeInternal=TRUE, xStopCmd ver",
    },
    "fat.sm.t6.test": {
        "de": "Zykluswiederholung im Automatikbetrieb",
        "en": "Cycle repeat in auto mode",
        "tr": "Otomatik modda çevrim tekrarı",
    },
    "fat.sm.t6.action": {
        "de": "Zyklus beendet, Werkstück vorhanden TRUE",
        "en": "Cycle done, workpiece presence TRUE",
        "tr": "Çevrim bitti, iş parçası mevcut TRUE",
    },
    "fat.sm.t6.expected": {
        "de": "READY (20) → automatischer Neustart",
        "en": "READY (20) → auto restart",
        "tr": "READY (20) → otomatik yeniden başlama",
    },
    "fat.sm.t7.test": {
        "de": "Reset im FAULT-Zustand",
        "en": "Reset in FAULT state",
        "tr": "FAULT durumunda reset",
    },
    "fat.sm.t7.action": {
        "de": "Fehlerbedingung beheben, xResetCmd geben",
        "en": "Clear error condition, issue xResetCmd",
        "tr": "Hata koşulunu gider, xResetCmd ver",
    },
    "fat.sm.t8.test": {
        "de": "EMERGENCY → Rückkehr in Normalbetrieb",
        "en": "EMERGENCY → normal return",
        "tr": "EMERGENCY → normale dönüş",
    },
    "fat.sm.t8.action": {
        "de": "NOT-HALT entriegeln + Reset-Befehl geben",
        "en": "Release E-stop + issue reset command",
        "tr": "E-stop'u bırak + reset komutu ver",
    },
    "fat.sm.t9.test": {
        "de": "Wiederanlauf aus undefiniertem Zustand",
        "en": "Undefined state recovery",
        "tr": "Tanımsız durumdan kurtarma",
    },
    "fat.sm.t9.start": {
        "de": "Beliebig", "en": "Any", "tr": "Herhangi",
    },
    "fat.sm.t9.action": {
        "de": "iState auf ungültigen Wert forcen (z. B. 500)",
        "en": "Force iState to invalid value (e.g. 500)",
        "tr": "iState'i geçersiz değere force et (örn. 500)",
    },
    "fat.sm.t9.expected": {
        "de": "FAULT (900) — ELSE-Zweig muss greifen",
        "en": "FAULT (900) — ELSE branch must activate",
        "tr": "FAULT (900) — ELSE dalı devreye girmeli",
    },
    "fat.sm.t10.test": {
        "de": "Periodische Watchdog-Prüfung",
        "en": "Watchdog periodic test",
        "tr": "Periyodik watchdog testi",
    },
    "fat.sm.t10.action": {
        "de": "Positionssignal FALSE halten, 15 s warten",
        "en": "Keep approach position signal FALSE, wait 15 s",
        "tr": "Pozisyon sinyalini FALSE tut, 15 s bekle",
    },
    "fat.sm.t10.expected": {
        "de": "FAULT (900), Fehlercode 301",
        "en": "FAULT (900), error code 301",
        "tr": "FAULT (900), hata kodu 301",
    },

    # ── FAT: stress rows (scenario / method / expected) ───────────────────
    "fat.stress.t1.scenario": {
        "de": "Schnelles START/STOP-Spam",
        "en": "Fast START/STOP spam",
        "tr": "Hızlı START/STOP spam",
    },
    "fat.stress.t1.method": {
        "de": "In IDLE 10-mal hintereinander START drücken (0,5-s-Takt)",
        "en": "Press START 10 times in a row while in IDLE (0.5 s interval)",
        "tr": "IDLE'da art arda 10 kez START'a bas (0,5 s aralık)",
    },
    "fat.stress.t1.expected": {
        "de": "Programm stürzt nicht ab, letzter gültiger Befehl wird übernommen, "
              "Zustand bleibt konsistent",
        "en": "Program does not crash, last valid command applied, state remains "
              "consistent",
        "tr": "Program çökmez, son geçerli komut uygulanır, durum tutarlı kalır",
    },
    "fat.stress.t2.scenario": {
        "de": "Zyklus-Stabilitätstest",
        "en": "Cycle stability test",
        "tr": "Çevrim kararlılık testi",
    },
    "fat.stress.t2.method": {
        "de": "100 vollständige Zyklen im Automatikbetrieb fahren, IO je Zyklus "
              "protokollieren",
        "en": "Run 100 complete cycles in auto mode, log IO each cycle",
        "tr": "Otomatik modda 100 tam çevrim koştur, her çevrimde IO logla",
    },
    "fat.stress.t2.expected": {
        "de": "Jeder Zyklus in gleicher Zeit, kein FAULT, Zähler inkrementiert "
              "korrekt",
        "en": "Each cycle completes in same time, no FAULT, counter increments "
              "correctly",
        "tr": "Her çevrim aynı sürede biter, FAULT yok, sayaç doğru artar",
    },
    "fat.stress.t3.scenario": {
        "de": "Parallele Alarmauslösung",
        "en": "Parallel alarm generation",
        "tr": "Paralel alarm üretimi",
    },
    "fat.stress.t3.method": {
        "de": "NOT-HALT + Tür offen + Antriebsfehler gleichzeitig forcen",
        "en": "Force E-stop + door open + drive failure simultaneously",
        "tr": "E-stop + kapı açık + sürücü arızasını aynı anda force et",
    },
    "fat.stress.t3.expected": {
        "de": "Fehler höchster Priorität (NOT-HALT=Kat. 0) gewinnt, keine "
              "widersprüchlichen Fehler",
        "en": "Highest priority error (E-stop=Cat0) wins, no conflicting errors",
        "tr": "En yüksek öncelikli hata (E-stop=Kat0) kazanır, çelişen hata yok",
    },
    "fat.stress.t4.scenario": {
        "de": "Spannungsausfall / CPU-Neustart",
        "en": "Power loss / CPU restart",
        "tr": "Güç kaybı / CPU yeniden başlatma",
    },
    "fat.stress.t4.method": {
        "de": "CPU während der Bearbeitung zurücksetzen (STOP → RUN)",
        "en": "Reset CPU during processing (STOP → RUN)",
        "tr": "İşleme sırasında CPU'yu resetle (STOP → RUN)",
    },
    "fat.stress.t4.expected": {
        "de": "Initialisierung mit xFirstScan löscht Zustände, Start aus sicherem "
              "Zustand (IDLE)",
        "en": "Initialization with xFirstScan clears state, starts from safe "
              "state (IDLE)",
        "tr": "xFirstScan ile başlatma durumları temizler, güvenli durumdan "
              "(IDLE) başlar",
    },
    "fat.stress.t5.scenario": {
        "de": "Simulation Leitungsbruch Analogsensor",
        "en": "Analog sensor cable break simulation",
        "tr": "Analog sensör kablo kopması simülasyonu",
    },
    "fat.stress.t5.method": {
        "de": "AI-Eingang auf -32768 (Underrange) forcen",
        "en": "Force AI input to -32768 (underrange) value",
        "tr": "AI girişini -32768 (underrange) değerine force et",
    },
    "fat.stress.t5.expected": {
        "de": "Programm begrenzt negativen Wert auf 0 oder Untergrenze, Alarm "
              "wird ausgelöst",
        "en": "Program clamps negative value to 0 or lower limit, generates alarm",
        "tr": "Program negatif değeri 0'a veya alt sınıra sınırlar, alarm üretir",
    },
    "fat.stress.t6.scenario": {
        "de": "Sofortiger Wechsel Hand- → Automatikbetrieb",
        "en": "Manual mode → auto mode instant transition",
        "tr": "Manuel mod → otomatik mod ani geçiş",
    },
    "fat.stress.t6.method": {
        "de": "Während der Bearbeitung von Hand- auf Automatikbetrieb umschalten",
        "en": "Switch from manual to auto mode during processing",
        "tr": "İşleme sırasında manuelden otomatiğe geç",
    },
    "fat.stress.t6.expected": {
        "de": "Erst sicherer Halt; Moduswechsel nur in IDLE/READY",
        "en": "Safe stop first; mode change only occurs in IDLE/READY",
        "tr": "Önce güvenli duruş; mod değişimi sadece IDLE/READY'de",
    },
    "fat.stress.t7.scenario": {
        "de": "Watchdog-Lasttest",
        "en": "Watchdog load test",
        "tr": "Watchdog yük testi",
    },
    "fat.stress.t7.method": {
        "de": "OB1-Zyklus absichtlich verlängern (innere Schleife), WDT überwachen",
        "en": "Deliberately extend OB1 cycle (add inner loop), monitor WDT",
        "tr": "OB1 çevrimini bilinçli uzat (iç döngü ekle), WDT'yi izle",
    },
    "fat.stress.t7.expected": {
        "de": "CPU erzeugt kein OB80 (Timeout); falls doch, wird der Alarm in DB "
              "protokolliert",
        "en": "CPU does not generate OB80 (timeout error); if it does, alarm is "
              "logged to DB",
        "tr": "CPU OB80 (timeout) üretmez; üretirse alarm DB'ye loglanır",
    },
    "fat.stress.t8.scenario": {
        "de": "HMI getrennt",
        "en": "HMI disconnected state",
        "tr": "HMI bağlantısı kopuk",
    },
    "fat.stress.t8.method": {
        "de": "HMI-Variablen (HMI_*) nicht mehr aktualisieren, nur SPS laufen "
              "lassen",
        "en": "Stop updating HMI variables (HMI_*), let only PLC run",
        "tr": "HMI değişkenlerini (HMI_*) güncellemeyi durdur, sadece PLC çalışsın",
    },
    "fat.stress.t8.expected": {
        "de": "Programm läuft HMI-unabhängig weiter; NULL/alte HMI-Werte kehren "
              "in sicheren Anfangszustand zurück",
        "en": "Program continues HMI-independent operation, NULL/old values in "
              "HMI return to safe start",
        "tr": "Program HMI'dan bağımsız çalışmaya devam eder; HMI'daki NULL/eski "
              "değerler güvenli başlangıca döner",
    },
    "fat.stress.t9.scenario": {
        "de": "Alle DI-Eingänge gleichzeitig TRUE",
        "en": "All DI inputs TRUE simultaneously",
        "tr": "Tüm DI girişleri aynı anda TRUE",
    },
    "fat.stress.t9.method": {
        "de": "Alle Digitaleingänge gleichzeitig auf TRUE forcen",
        "en": "Force all digital inputs to TRUE at same time",
        "tr": "Tüm dijital girişleri aynı anda TRUE'ya force et",
    },
    "fat.stress.t9.expected": {
        "de": "Zustandsmaschine gerät nicht in undefinierten Zustand; "
              "Sicherheitslogik bleibt dominant",
        "en": "State machine does not enter undefined state; safety logic "
              "remains dominant",
        "tr": "Durum makinesi tanımsız duruma girmez; güvenlik mantığı baskın "
              "kalır",
    },
    "fat.stress.t10.scenario": {
        "de": "Dauerbetätigung der Reset-Taste",
        "en": "Continuous reset button press",
        "tr": "Sürekli reset butonuna basma",
    },
    "fat.stress.t10.method": {
        "de": "xResetCmd während der Bearbeitung TRUE halten",
        "en": "Keep xResetCmd TRUE during processing",
        "tr": "İşleme sırasında xResetCmd'yi TRUE tut",
    },
    "fat.stress.t10.expected": {
        "de": "Reset nur in FAULT(900) oder IDLE(0) wirksam; in anderen "
              "Zuständen ignoriert",
        "en": "Reset only effective in FAULT(900) or IDLE(0) state; ignored in "
              "other states",
        "tr": "Reset sadece FAULT(900) veya IDLE(0) durumunda etkili; diğer "
              "durumlarda yok sayılır",
    },

    # ── SAT: loop check ───────────────────────────────────────────────────
    "sat.loop.row_di": {
        "de": "Loop-Check Digitaleingang: {name} — Geber am Feldgerät betätigen",
        "en": "Loop check digital input: {name} — actuate sensor at field device",
        "tr": "Loop check dijital giriş: {name} — saha cihazında sensörü tetikle",
    },
    "sat.loop.row_do": {
        "de": "Loop-Check Digitalausgang: {name} — Ausgang von der SPS ansteuern",
        "en": "Loop check digital output: {name} — drive output from PLC",
        "tr": "Loop check dijital çıkış: {name} — çıkışı PLC'den sür",
    },
    "sat.loop.row_ai": {
        "de": "Loop-Check Analogeingang: {name} — Prozesswert am Messumformer "
              "einspeisen",
        "en": "Loop check analog input: {name} — inject process value at "
              "transmitter",
        "tr": "Loop check analog giriş: {name} — transmitterde proses değeri "
              "uygula",
    },
    "sat.loop.row_ao": {
        "de": "Loop-Check Analogausgang: {name} — Sollwert ausgeben, am "
              "Stellglied messen",
        "en": "Loop check analog output: {name} — output setpoint, measure at "
              "actuator",
        "tr": "Loop check analog çıkış: {name} — set değeri ver, aktüatörde ölç",
    },
    "sat.loop.expected_di": {
        "de": "Signal erscheint an {addr}, korrekte Polarität, HMI-Anzeige stimmt",
        "en": "Signal appears at {addr}, correct polarity, HMI display matches",
        "tr": "{addr} adresinde sinyal görünür, polarite doğru, HMI göstergesi "
              "uyumlu",
    },
    "sat.loop.expected_do": {
        "de": "Feldgerät schaltet, Rückmeldung an {addr} korrekt",
        "en": "Field device switches, feedback at {addr} correct",
        "tr": "Saha cihazı anahtarlar, {addr} geri bildirimi doğru",
    },
    "sat.loop.expected_ai": {
        "de": "Skalierter Wert in der SPS = eingespeister Wert (±1 %)",
        "en": "Scaled PLC value = injected value (±1%)",
        "tr": "PLC'deki ölçekli değer = uygulanan değer (±%1)",
    },
    "sat.loop.expected_ao": {
        "de": "Gemessener Wert am Stellglied = Sollwert (±1 %)",
        "en": "Measured value at actuator = setpoint (±1%)",
        "tr": "Aktüatörde ölçülen değer = set değeri (±%1)",
    },
    "sat.loop.no_signals": {
        "de": "Keine Signaltabelle in RD01 gefunden — Loop-Check-Liste ist vom "
              "Inbetriebnehmer manuell zu erstellen.",
        "en": "No signal table found in RD01 — the loop check list must be "
              "created manually by the commissioning engineer.",
        "tr": "RD01'de sinyal tablosu bulunamadı — loop check listesi devreye "
              "alma mühendisi tarafından elle oluşturulmalıdır.",
    },
    "fat.io.no_signals": {
        "de": "Keine Signaltabelle in RD01 gefunden — die E/A-Prüfliste ist "
              "vor dem FAT manuell zu ergänzen (Abschnitt nicht entfernen).",
        "en": "No signal table found in RD01 — the I/O check list must be "
              "completed manually before the FAT (do not remove this section).",
        "tr": "RD01'de sinyal tablosu bulunamadı — G/Ç kontrol listesi FAT "
              "öncesi elle tamamlanmalıdır (bu bölüm kaldırılmamalı).",
    },

    # ── SAT: motor rotation ───────────────────────────────────────────────
    "sat.motor.bump": {
        "de": "Drehrichtungstest (Tippbetrieb) — Antrieb kurz ansteuern",
        "en": "Rotation test (bump test) — jog drive briefly",
        "tr": "Dönüş yönü testi (bump test) — sürücüyü kısa tetikle",
    },
    "sat.motor.bump.expected": {
        "de": "Drehrichtung entspricht Prozessrichtung (Pfeil/Kennzeichnung); "
              "bei Falschlauf: zwei Phasen tauschen und erneut prüfen",
        "en": "Rotation matches process direction (arrow/marking); if wrong: "
              "swap two phases and re-test",
        "tr": "Dönüş yönü proses yönüne uyar (ok/işaret); yanlışsa iki fazı "
              "değiştir ve tekrar test et",
    },
    "sat.motor.generic": {
        "de": "Alle Antriebe (RD01-DQ/AO-Liste) im Tippbetrieb auf Drehrichtung "
              "prüfen",
        "en": "Check rotation direction of all drives (RD01 DQ/AO list) in jog "
              "mode",
        "tr": "Tüm sürücülerin (RD01 DQ/AO listesi) dönüş yönünü jog modunda "
              "kontrol et",
    },

    # ── SAT: sensor alignment ─────────────────────────────────────────────
    "sat.sensor.limit": {
        "de": "Endschalter mechanisch justieren — Schaltpunkt am realen Anschlag",
        "en": "Mechanically align limit switches — switching point at real stop",
        "tr": "Limit switch'leri mekanik hizala — anahtarlama noktası gerçek "
              "dayamada",
    },
    "sat.sensor.limit.expected": {
        "de": "Schaltpunkt reproduzierbar, Signal stabil (kein Prellen im "
              "Dauertest)",
        "en": "Switching point reproducible, signal stable (no bounce in "
              "endurance check)",
        "tr": "Anahtarlama noktası tekrarlanabilir, sinyal kararlı (dayanım "
              "testinde sıçrama yok)",
    },
    "sat.sensor.analog_cal": {
        "de": "Analogsensoren gegen Referenzmessgerät kalibrieren (2-Punkt)",
        "en": "Calibrate analog sensors against reference instrument (2-point)",
        "tr": "Analog sensörleri referans ölçü aletine karşı kalibre et (2 nokta)",
    },
    "sat.sensor.analog_cal.expected": {
        "de": "Abweichung ≤ Toleranz laut Datenblatt; Werte in SPS und HMI "
              "identisch",
        "en": "Deviation ≤ datasheet tolerance; PLC and HMI values identical",
        "tr": "Sapma ≤ veri sayfası toleransı; PLC ve HMI değerleri aynı",
    },

    # ── SAT: real safety chain ────────────────────────────────────────────
    "sat.safety.estop_real": {
        "de": "JEDEN NOT-HALT-Taster der Anlage einzeln betätigen (real, keine "
              "Simulation)",
        "en": "Actuate EVERY E-stop button of the plant individually (real, no "
              "simulation)",
        "tr": "Tesisteki HER E-stop butonunu tek tek fiziksel olarak tetikle "
              "(simülasyon değil)",
    },
    "sat.safety.estop_real.expected": {
        "de": "Sichere Abschaltung gemäß Stopp-Kategorie (EN 60204-1); "
              "Wiederanlauf nur nach manuellem Reset",
        "en": "Safe shutdown per stop category (EN 60204-1); restart only after "
              "manual reset",
        "tr": "Stop kategorisine göre güvenli kapanma (EN 60204-1); yeniden "
              "başlama sadece manuel reset sonrası",
    },
    "sat.safety.door_real": {
        "de": "Jede Schutztür / jeden Sicherheitskreis real öffnen — Zuhaltung "
              "und Stoppverhalten prüfen",
        "en": "Physically open every guard door / safety circuit — check guard "
              "locking and stop behavior",
        "tr": "Her koruma kapısını / güvenlik devresini fiziksel olarak aç — "
              "kilitleme ve durma davranışını kontrol et",
    },
    "sat.safety.door_real.expected": {
        "de": "Gefahrbringende Bewegung stoppt innerhalb der projektierten Zeit; "
              "Zuhaltung gibt erst bei Stillstand frei",
        "en": "Hazardous motion stops within the engineered time; guard lock "
              "releases only at standstill",
        "tr": "Tehlikeli hareket öngörülen süre içinde durur; kilit ancak "
              "duruşta açılır",
    },
    "sat.safety.wiring": {
        "de": "Sicherheitsverdrahtung gegen Stromlaufplan prüfen "
              "(Kanalzuordnung, Querschluss-Erkennung)",
        "en": "Verify safety wiring against circuit diagram (channel "
              "assignment, cross-short detection)",
        "tr": "Güvenlik kablajını devre şemasına karşı doğrula (kanal ataması, "
              "çapraz kısa devre algılama)",
    },
    "sat.safety.wiring.expected": {
        "de": "Verdrahtung stimmt mit Plan überein; Querschluss wird erkannt "
              "und gemeldet",
        "en": "Wiring matches diagram; cross-short is detected and reported",
        "tr": "Kablaj şemayla uyumlu; çapraz kısa devre algılanır ve raporlanır",
    },

    # ── SAT: drive parameters ─────────────────────────────────────────────
    "sat.drive.params": {
        "de": "Antriebsparameter mit Sollliste abgleichen (Rampen, Min/Max-"
              "Frequenz, Motorschutz, Stromgrenzen)",
        "en": "Compare drive parameters with target list (ramps, min/max "
              "frequency, motor protection, current limits)",
        "tr": "Sürücü parametrelerini hedef listeyle karşılaştır (rampalar, "
              "min/maks frekans, motor koruması, akım limitleri)",
    },
    "sat.drive.params.expected": {
        "de": "Alle Parameter = Sollwert; Abweichungen dokumentiert und "
              "freigegeben",
        "en": "All parameters = target value; deviations documented and "
              "approved",
        "tr": "Tüm parametreler = hedef değer; sapmalar dokümante ve onaylı",
    },
    "sat.drive.protection": {
        "de": "Schutzfunktionen real auslösen (Motorschutzschalter / "
              "Überlastsimulation, sofern gefahrlos möglich)",
        "en": "Trigger protection functions for real (motor protection switch / "
              "overload simulation where safely possible)",
        "tr": "Koruma fonksiyonlarını gerçekten tetikle (motor koruma şalteri / "
              "güvenliyse aşırı yük simülasyonu)",
    },
    "sat.drive.protection.expected": {
        "de": "Antrieb schaltet ab, Störmeldung erscheint an SPS und HMI",
        "en": "Drive trips, fault message appears on PLC and HMI",
        "tr": "Sürücü devreden çıkar, arıza mesajı PLC ve HMI'da görünür",
    },

    # ── SAT: network / HMI ────────────────────────────────────────────────
    "sat.net.topology": {
        "de": "PROFINET-Topologie mit Projektierung vergleichen (Gerätenamen, "
              "IP-Adressen, Ringredundanz falls vorhanden)",
        "en": "Compare PROFINET topology with engineering (device names, IP "
              "addresses, ring redundancy if present)",
        "tr": "PROFINET topolojisini projeyle karşılaştır (cihaz adları, IP "
              "adresleri, varsa ring yedekliliği)",
    },
    "sat.net.topology.expected": {
        "de": "Alle Teilnehmer erreichbar, keine BF/SF-LEDs, Diagnosepuffer ohne "
              "Netzwerkfehler",
        "en": "All nodes reachable, no BF/SF LEDs, diagnostic buffer free of "
              "network errors",
        "tr": "Tüm düğümler erişilebilir, BF/SF LED'i yok, tanı tamponunda ağ "
              "hatası yok",
    },
    "sat.net.hmi_screens": {
        "de": "HMI-Bilder gegen reale Anlage prüfen (Anzeigen, Bedienelemente, "
              "Alarmanzeige, Sprachumschaltung)",
        "en": "Verify HMI screens against the real plant (indications, "
              "controls, alarm display, language switching)",
        "tr": "HMI ekranlarını gerçek tesise karşı doğrula (göstergeler, "
              "kumandalar, alarm ekranı, dil değişimi)",
    },
    "sat.net.hmi_screens.expected": {
        "de": "Alle Anzeigen entsprechen dem Anlagenzustand; Bedienhandlungen "
              "wirken wie projektiert",
        "en": "All indications match plant state; operator actions behave as "
              "engineered",
        "tr": "Tüm göstergeler tesis durumuyla uyumlu; operatör eylemleri "
              "tasarlandığı gibi çalışır",
    },
    "sat.net.interlock_chain": {
        "de": "Anlagenübergreifende Verriegelungen mit Nachbargewerken testen "
              "(Förderstrecke, übergeordnete Steuerung)",
        "en": "Test cross-plant interlocks with adjacent systems (conveyor "
              "line, supervisory control)",
        "tr": "Komşu sistemlerle tesisler arası kilitlemeleri test et (konveyör "
              "hattı, üst seviye kontrol)",
    },
    "sat.net.interlock_chain.expected": {
        "de": "Verriegelungen wirken in beide Richtungen; keine undefinierten "
              "Zustände an den Schnittstellen",
        "en": "Interlocks act in both directions; no undefined states at the "
              "interfaces",
        "tr": "Kilitlemeler iki yönde de çalışır; arayüzlerde tanımsız durum yok",
    },

    # ── SAT: backup & handover ────────────────────────────────────────────
    "sat.backup.full": {
        "de": "Vollständige Datensicherung erstellen (TIA-Projekt, HMI, "
              "Antriebsparameter) und auf Übergabemedium ablegen",
        "en": "Create complete backup (TIA project, HMI, drive parameters) and "
              "store on handover medium",
        "tr": "Tam yedek oluştur (TIA projesi, HMI, sürücü parametreleri) ve "
              "teslim ortamına kaydet",
    },
    "sat.backup.full.expected": {
        "de": "Sicherung vollständig, Prüfsumme/Archiv dokumentiert",
        "en": "Backup complete, checksum/archive documented",
        "tr": "Yedek tam, sağlama/arşiv dokümante",
    },
    "sat.backup.restore": {
        "de": "Wiederherstellungstest: Sicherung auf Testgerät/zweite CPU "
              "zurückspielen oder Upload-Vergleich durchführen",
        "en": "Restore test: load backup onto test device/second CPU or perform "
              "upload comparison",
        "tr": "Geri yükleme testi: yedeği test cihazına/ikinci CPU'ya yükle veya "
              "upload karşılaştırması yap",
    },
    "sat.backup.restore.expected": {
        "de": "Wiederherstellung erfolgreich; Projekt identisch (Vergleich ohne "
              "Differenzen)",
        "en": "Restore successful; project identical (comparison shows no "
              "differences)",
        "tr": "Geri yükleme başarılı; proje birebir (karşılaştırmada fark yok)",
    },
    "sat.backup.docs": {
        "de": "Dokumentation übergeben: Stromlaufpläne (as-built), IO-Liste, "
              "Parameterlisten, Bedienungsanleitung",
        "en": "Hand over documentation: circuit diagrams (as-built), IO list, "
              "parameter lists, operating manual",
        "tr": "Dokümantasyonu teslim et: devre şemaları (as-built), IO listesi, "
              "parametre listeleri, kullanım kılavuzu",
    },
    "sat.backup.docs.expected": {
        "de": "Betreiber bestätigt Vollständigkeit per Unterschrift",
        "en": "Operator confirms completeness by signature",
        "tr": "İşletmeci eksiksizliği imzayla onaylar",
    },

    # ── SAT: cybersecurity (IEC 62443 / NIS2) — Faz 3 ─────────────────────
    "sat.cyber.access_levels": {
        "de": "TIA-Portal-Schutzstufen konfiguriert (Lese-/Schreibschutz, "
              "HMI-Zugriff) und Passwörter dokumentiert hinterlegt",
        "en": "TIA Portal protection levels configured (read/write protection, "
              "HMI access) and passwords stored in documented vault",
        "tr": "TIA Portal koruma seviyeleri yapılandırıldı (okuma/yazma "
              "koruması, HMI erişimi) ve şifreler dokümante kasada",
    },
    "sat.cyber.access_levels.expected": {
        "de": "Zugriff ohne Passwort nicht möglich; Stufenkonzept entspricht "
              "Vorgabe",
        "en": "Access without password impossible; level concept matches "
              "specification",
        "tr": "Şifresiz erişim mümkün değil; seviye konsepti şartnameye uygun",
    },
    "sat.cyber.default_pw": {
        "de": "Alle Default-Passwörter geändert (CPU-Display, HMI, Switches, "
              "Antriebe, Fernwartung)",
        "en": "All default passwords changed (CPU display, HMI, switches, "
              "drives, remote access)",
        "tr": "Tüm varsayılan şifreler değiştirildi (CPU ekranı, HMI, "
              "switch'ler, sürücüler, uzak erişim)",
    },
    "sat.cyber.default_pw.expected": {
        "de": "Kein Gerät mit Werkspasswort erreichbar",
        "en": "No device reachable with factory password",
        "tr": "Hiçbir cihaza fabrika şifresiyle erişilemiyor",
    },
    "sat.cyber.knowhow": {
        "de": "Know-how-Schutz für sicherheits-/IP-kritische Bausteine aktiv",
        "en": "Block know-how protection active for safety/IP-critical blocks",
        "tr": "Güvenlik/IP-kritik bloklarda know-how koruması aktif",
    },
    "sat.cyber.knowhow.expected": {
        "de": "Geschützte Bausteine ohne Passwort nicht einsehbar",
        "en": "Protected blocks not viewable without password",
        "tr": "Korumalı bloklar şifresiz görüntülenemez",
    },
    "sat.cyber.ports": {
        "de": "Offene Ports/Dienste geprüft (Webserver, PUT/GET, SNMP) — nicht "
              "benötigte Dienste deaktiviert",
        "en": "Open ports/services checked (web server, PUT/GET, SNMP) — unused "
              "services disabled",
        "tr": "Açık portlar/servisler kontrol edildi (web sunucu, PUT/GET, "
              "SNMP) — gereksiz servisler kapatıldı",
    },
    "sat.cyber.ports.expected": {
        "de": "Nur projektierte Dienste aktiv; Ergebnis dokumentiert",
        "en": "Only engineered services active; result documented",
        "tr": "Sadece tasarlanan servisler aktif; sonuç dokümante",
    },
    "sat.cyber.backup_tested": {
        "de": "Sicherung erstellt UND Wiederherstellung erprobt "
              "(Ransomware-Vorsorge)",
        "en": "Backup created AND restore rehearsed (ransomware precaution)",
        "tr": "Yedek alındı VE geri yükleme denendi (fidye yazılımı önlemi)",
    },
    "sat.cyber.backup_tested.expected": {
        "de": "Wiederherstellung nachweislich erfolgreich (siehe Abschnitt "
              "Datensicherung)",
        "en": "Restore verifiably successful (see Backup section)",
        "tr": "Geri yükleme kanıtlı şekilde başarılı (bkz. Yedekleme bölümü)",
    },
    "sat.cyber.network_seg": {
        "de": "Netzwerksegmentierung/Firewall-Konzept geprüft (Zellenschutz, "
              "keine Direktverbindung Office ↔ Anlagennetz)",
        "en": "Network segmentation/firewall concept checked (cell protection, "
              "no direct office ↔ plant network link)",
        "tr": "Ağ ayrımı/güvenlik duvarı konsepti kontrol edildi (hücre "
              "koruması, ofis ↔ tesis ağı direkt bağlantı yok)",
    },
    "sat.cyber.network_seg.expected": {
        "de": "Anlagennetz nur über definierte Übergänge erreichbar; Konzept "
              "dokumentiert",
        "en": "Plant network reachable only via defined gateways; concept "
              "documented",
        "tr": "Tesis ağına sadece tanımlı geçitlerden erişim; konsept dokümante",
    },

    # ── prechecks (script_protocol_generator) ─────────────────────────────
    "pre.cpu_power": {
        "de": "CPU-Montage und Spannungsversorgung geprüft",
        "en": "CPU mounting and power connection checked",
        "tr": "CPU montajı ve güç bağlantısı kontrol edildi",
    },
    "pre.cpu_power.expected": {
        "de": "CPU im STOP-Modus, RUN-LED leuchtet nicht grün",
        "en": "CPU in STOP mode, no green RUN LED",
        "tr": "CPU STOP modunda, yeşil RUN LED'i yanmıyor",
    },
    "pre.cables": {
        "de": "Alle Kabel- und Steckverbindungen nachgezogen",
        "en": "All cable and connector connections tightened",
        "tr": "Tüm kablo ve konnektör bağlantıları sıkıldı",
    },
    "pre.cables.expected": {
        "de": "Keine losen Leitungen",
        "en": "No loose cables",
        "tr": "Gevşek kablo yok",
    },
    "pre.profinet": {
        "de": "PROFINET-Netzwerkverkabelung abgeschlossen",
        "en": "PROFINET network wiring completed",
        "tr": "PROFINET ağ kablajı tamamlandı",
    },
    "pre.profinet.expected": {
        "de": "Angeschlossene IO-Geräte ohne leuchtende BF-LED",
        "en": "Connected IO devices have no BF LED lit",
        "tr": "Bağlı IO cihazlarında BF LED'i yanmıyor",
    },
    "pre.tia_compile": {
        "de": "Projekt in TIA Portal {ver} geöffnet, fehlerfrei übersetzt",
        "en": "Project opened in TIA Portal {ver} and compiles without errors",
        "tr": "Proje TIA Portal {ver} ile açıldı ve hatasız derleniyor",
    },
    "pre.tia_compile.expected": {
        "de": "0 Übersetzungsfehler",
        "en": "0 compile errors, 0 errors",
        "tr": "0 derleme hatası",
    },
    "pre.download": {
        "de": "Projekt in die CPU geladen (Download)",
        "en": "Project downloaded to the CPU (Download)",
        "tr": "Proje CPU'ya yüklendi (Download)",
    },
    "pre.download.expected": {
        "de": "Download erfolgreich",
        "en": "Download successful",
        "tr": "Download başarılı",
    },
    "pre.run_mode": {
        "de": "CPU in RUN-Modus geschaltet",
        "en": "CPU set to RUN mode",
        "tr": "CPU RUN moduna alındı",
    },
    "pre.run_mode.expected": {
        "de": "RUN-LED leuchtet grün",
        "en": "RUN LED lit green",
        "tr": "RUN LED'i yeşil yanıyor",
    },
    "pre.fcpu_check": {
        "de": "F-CPU: Konsistenzprüfung des Sicherheitsprogramms durchgeführt",
        "en": "F-CPU: Safety program Consistency Check performed",
        "tr": "F-CPU: Güvenlik programı tutarlılık kontrolü yapıldı",
    },
    "pre.fcpu_check.expected": {
        "de": "F-CPU im Modus „SAFE“, F-DB-Signatur stimmt überein",
        "en": "F-CPU in 'SAFE' mode, F-DB signature matches",
        "tr": "F-CPU 'SAFE' modunda, F-DB imzası eşleşiyor",
    },
    "pre.sat_field_devices": {
        "de": "Alle Feldgeräte montiert, angeschlossen und mit Spannung versorgt",
        "en": "All field devices mounted, wired and powered",
        "tr": "Tüm saha cihazları monte, bağlı ve enerjili",
    },
    "pre.sat_field_devices.expected": {
        "de": "Keine offenen Klemmen; Gerätestatus-LEDs fehlerfrei",
        "en": "No open terminals; device status LEDs error-free",
        "tr": "Açık klemens yok; cihaz durum LED'leri hatasız",
    },
    "pre.sat_asbuilt": {
        "de": "As-built-Unterlagen (Stromlaufplan, IO-Liste) auf Stand und vor Ort",
        "en": "As-built documentation (circuit diagram, IO list) current and on site",
        "tr": "As-built dokümantasyon (devre şeması, IO listesi) güncel ve sahada",
    },
    "pre.sat_asbuilt.expected": {
        "de": "Revisionsstand entspricht der gelieferten Anlage",
        "en": "Revision matches the delivered plant",
        "tr": "Revizyon teslim edilen tesisle uyumlu",
    },

    # ── function tests (script_protocol_generator) ────────────────────────
    "func.normal": {
        "de": "{btype} „{bname}“ — Szenario Normalbetrieb",
        "en": "{btype} '{bname}' — Normal operation scenario",
        "tr": "{btype} '{bname}' — Normal çalışma senaryosu",
    },
    "func.normal.expected": {
        "de": "„{bname}“ läuft fehlerfrei, Ausgangswerte im erwarteten Bereich",
        "en": "'{bname}' runs without errors, output values within expected range",
        "tr": "'{bname}' hatasız çalışır, çıkış değerleri beklenen aralıkta",
    },
    "func.fault": {
        "de": "{btype} „{bname}“ — Fehlerszenario (Enable=FALSE / NOT-HALT)",
        "en": "{btype} '{bname}' — Fault scenario (Enable=FALSE / E-Stop)",
        "tr": "{btype} '{bname}' — Hata senaryosu (Enable=FALSE / E-Stop)",
    },
    "func.fault.expected": {
        "de": "„{bname}“ wartet im sicheren Zustand, Ausgänge inaktiv",
        "en": "'{bname}' waits in a safe state, outputs inactive",
        "tr": "'{bname}' güvenli durumda bekler, çıkışlar pasif",
    },

    # ── alarm tests (script_protocol_generator) ───────────────────────────
    "alarm.test": {
        "de": "Alarmtest: „{msg}“",
        "en": "Alarm test: '{msg}'",
        "tr": "Alarm testi: '{msg}'",
    },
    "alarm.test.expected": {
        "de": "Alarm „{msg}“ erscheint an HMI/SCADA und ist quittierbar",
        "en": "'{msg}' alarm is displayed on HMI/SCADA and can be acknowledged",
        "tr": "'{msg}' alarmı HMI/SCADA'da görünür ve onaylanabilir",
    },
    "alarm.no_table_warning": {
        "de": "Keine Alarmtabelle in RD08_Alarm.md gefunden — Alarmtest-Abschnitt ist leer",
        "en": "No alarm table found in RD08_Alarm.md — Alarm test section is empty",
        "tr": "RD08_Alarm.md içinde alarm tablosu bulunamadı — Alarm test bölümü boş",
    },
    "io.no_table_warning": {
        "de": "Keine Signaltabelle in RD01_IO_List.md gefunden — IO-Test-Abschnitt ist leer",
        "en": "No signal table found in RD01_IO_List.md — IO test section is empty",
        "tr": "RD01_IO_List.md içinde sinyal tablosu bulunamadı — IO test bölümü boş",
    },

    # ── IO test rows (script_protocol_generator) ──────────────────────────
    "io.test_input": {
        "de": "Digitaleingangstest: {name}",
        "en": "Digital input test: {name}",
        "tr": "Dijital giriş testi: {name}",
    },
    "io.test_input.expected": {
        "de": "SPS zeigt {addr} = TRUE",
        "en": "PLC shows {addr} = TRUE",
        "tr": "PLC {addr} = TRUE gösterir",
    },
    "io.test_output": {
        "de": "Digitalausgangstest: {name}",
        "en": "Digital output test: {name}",
        "tr": "Dijital çıkış testi: {name}",
    },
    "io.test_output.expected": {
        "de": "Feldgerät aktiviert — SPS {addr} = TRUE",
        "en": "Field device activated — PLC {addr} = TRUE",
        "tr": "Saha cihazı aktif — PLC {addr} = TRUE",
    },
    "io.test_generic": {
        "de": "IO-Test: {name}",
        "en": "IO test: {name}",
        "tr": "IO testi: {name}",
    },
    "io.test_generic.expected": {
        "de": "SPS liest an {addr} den erwarteten Wert",
        "en": "PLC reads the expected value at {addr}",
        "tr": "PLC {addr} adresinde beklenen değeri okur",
    },

    # ── IEC 62682 alarm rationalization (Faz 5) ───────────────────────────
    "alarm62682.title": {
        "de": "Alarm-Rationalisierung (IEC 62682)",
        "en": "Alarm Rationalization (IEC 62682)",
        "tr": "Alarm Rasyonalizasyonu (IEC 62682)",
    },
    "alarm62682.intro": {
        "de": "Priorität, erwartete Bedienerreaktion und Alarmklasse je Alarm — "
              "Quelle: RD08.",
        "en": "Priority, expected operator response and alarm class per alarm — "
              "source: RD08.",
        "tr": "Alarm başına öncelik, beklenen operatör tepkisi ve alarm sınıfı — "
              "kaynak: RD08.",
    },
    "alarm62682.fill_instruction": {
        "de": "Mit „—“ markierte Felder fehlen in RD08 — vom Projektingenieur zu "
              "ergänzen (Werte werden NICHT automatisch erraten).",
        "en": "Fields marked \"—\" are missing in RD08 — to be completed by the "
              "project engineer (values are NOT guessed automatically).",
        "tr": "\"—\" işaretli alanlar RD08'de eksik — proje mühendisi "
              "tamamlamalıdır (değerler otomatik TAHMİN EDİLMEZ).",
    },
    "alarm62682.col_priority": {
        "de": "Priorität", "en": "Priority", "tr": "Öncelik",
    },
    "alarm62682.col_response": {
        "de": "Bedienerreaktion", "en": "Operator Response", "tr": "Operatör Tepkisi",
    },
    "alarm62682.col_class": {
        "de": "Alarmklasse (Prozess/Sicherheit/Diagnose)",
        "en": "Alarm Class (process/safety/diagnostic)",
        "tr": "Alarm Sınıfı (proses/güvenlik/tanı)",
    },

    # ── SISTEMA support package (Faz 2) ───────────────────────────────────
    "sistema.prep_title": {
        "de": "SISTEMA-Vorbereitungsliste",
        "en": "SISTEMA Preparation List",
        "tr": "SISTEMA Hazırlık Listesi",
    },
    "sistema.prep_intro": {
        "de": "Sicherheitsfunktionen aus RD05 als Eingabevorlage für die "
              "SISTEMA-Berechnung. Die Software erinnert und dokumentiert — "
              "**die Berechnung und die Unterschrift sind Aufgabe des "
              "Sicherheitsingenieurs.** Es findet KEINE automatische "
              "PL-Berechnung statt.",
        "en": "Safety functions from RD05 as an input template for the SISTEMA "
              "calculation. The software reminds and documents — **the "
              "calculation and the signature are the safety engineer's "
              "responsibility.** No automatic PL calculation is performed.",
        "tr": "SISTEMA hesabı için RD05'ten güvenlik fonksiyonları giriş "
              "şablonu. Yazılım hatırlatır ve belgeler — **hesap ve imza "
              "güvenlik mühendisinin sorumluluğundadır.** Otomatik PL hesabı "
              "YAPILMAZ.",
    },
    "sistema.col_function": {
        "de": "Sicherheitsfunktion", "en": "Safety Function", "tr": "Güvenlik Fonksiyonu",
    },
    "sistema.col_plr": {
        "de": "PLr (gefordert)", "en": "PLr (required)", "tr": "PLr (gereken)",
    },
    "sistema.col_signals": {
        "de": "Zugehörige Signale (RD01)", "en": "Related Signals (RD01)",
        "tr": "İlişkili Sinyaller (RD01)",
    },
    "sistema.col_achieved": {
        "de": "Erreichter PL", "en": "Achieved PL", "tr": "Ulaşılan PL",
    },
    "sistema.col_file": {
        "de": "SISTEMA-Datei", "en": "SISTEMA File", "tr": "SISTEMA Dosyası",
    },
    "sistema.col_engineer": {
        "de": "Ingenieur", "en": "Engineer", "tr": "Mühendis",
    },
    "sistema.no_signal_match": {
        "de": "(keine RD01-Zuordnung gefunden — manuell zuordnen)",
        "en": "(no RD01 match found — assign manually)",
        "tr": "(RD01 eşleşmesi bulunamadı — elle eşleyin)",
    },
    "sistema.no_plr_warning": {
        "de": "In RD05 wurde KEINE PLr-Angabe gefunden — PLr-Werte aus der "
              "Risikobeurteilung ergänzen, bevor die SISTEMA-Berechnung "
              "beginnt.",
        "en": "NO PLr information was found in RD05 — add the PLr values from "
              "the risk assessment before starting the SISTEMA calculation.",
        "tr": "RD05'te PLr tanımı bulunamadı — SISTEMA hesabına başlamadan "
              "önce risk değerlendirmesinden PLr değerlerini ekleyin.",
    },
    "sistema.section_title": {
        "de": "SISTEMA-Berechnung (Nachweis Performance Level)",
        "en": "SISTEMA Calculation (Performance Level Evidence)",
        "tr": "SISTEMA Hesabı (Performance Level Kanıtı)",
    },
    "sistema.pending_box": {
        "de": "SISTEMA-Verifikation: AUSSTEHEND — vor der Auslieferung "
              "abzuschließen. Für die unten markierten Sicherheitsfunktionen "
              "liegt noch kein SISTEMA-Nachweis (erreichter PL) vor.",
        "en": "SISTEMA verification: PENDING — to be completed before "
              "delivery. The safety functions marked below have no SISTEMA "
              "evidence (achieved PL) yet.",
        "tr": "SISTEMA doğrulaması: BEKLEMEDE — teslimden önce "
              "tamamlanacak. Aşağıda işaretli güvenlik fonksiyonları için "
              "henüz SISTEMA kanıtı (ulaşılan PL) yok.",
    },
    "sistema.record_note": {
        "de": "Einträge sind Ingenieurerklärungen (Datum + Name); die "
              "SISTEMA-Datei verbleibt beim Projekt.",
        "en": "Entries are engineer declarations (date + name); the SISTEMA "
              "file stays with the project.",
        "tr": "Kayıtlar mühendis beyanıdır (tarih + isim); SISTEMA dosyası "
              "projeyle birlikte saklanır.",
    },
    "sistema.no_plr_in_rd05": {
        "de": "Hinweis: RD05 enthält keine PLr-Angaben — der "
              "SISTEMA-Nachweisstatus kann nicht abgeleitet werden. PLr in "
              "RD05 ergänzen.",
        "en": "Note: RD05 contains no PLr information — the SISTEMA evidence "
              "status cannot be derived. Add PLr to RD05.",
        "tr": "Not: RD05'te PLr bilgisi yok — SISTEMA kanıt durumu "
              "türetilemiyor. RD05'e PLr ekleyin.",
    },

    # ── CE essential-modification assessment (Faz 4) ──────────────────────
    "ce.title": {
        "de": "Bewertung „Wesentliche Veränderung“ einer Maschine",
        "en": "Assessment of \"Essential Modification\" of a Machine",
        "tr": "Makinede \"Esaslı Değişiklik\" Değerlendirmesi",
    },
    "ce.disclaimer": {
        "de": "Diese Vorlage ersetzt KEINE rechtliche Bewertung. Entscheidung "
              "und Unterschrift liegen beim verantwortlichen Ingenieur bzw. "
              "bei der benannten fachkundigen Person. Grundlage: "
              "Interpretationspapier des BMAS zur wesentlichen Veränderung "
              "von Maschinen; Maschinenrichtlinie 2006/42/EG bzw. "
              "Maschinenverordnung (EU) 2023/1230.",
        "en": "This template does NOT replace a legal assessment. The decision "
              "and the signature rest with the responsible engineer or the "
              "designated competent person. Basis: the German BMAS "
              "interpretation paper on essential modification of machinery; "
              "Machinery Directive 2006/42/EC and Machinery Regulation (EU) "
              "2023/1230.",
        "tr": "Bu şablon hukuki değerlendirmenin YERİNE GEÇMEZ. Karar ve imza "
              "sorumlu mühendise ya da görevlendirilen yetkin kişiye aittir. "
              "Dayanak: BMAS makine esaslı değişiklik yorum belgesi; Makine "
              "Direktifi 2006/42/AT ve Makine Tüzüğü (EU) 2023/1230.",
    },
    "ce.machine_identity": {
        "de": "Maschinenidentifikation",
        "en": "Machine Identification",
        "tr": "Makine Kimliği",
    },
    "ce.field_machine": {
        "de": "Maschine / Anlage", "en": "Machine / Plant", "tr": "Makine / Tesis",
    },
    "ce.field_manufacturer": {
        "de": "Hersteller", "en": "Manufacturer", "tr": "Üretici",
    },
    "ce.field_serial": {
        "de": "Seriennummer", "en": "Serial Number", "tr": "Seri No",
    },
    "ce.field_year": {
        "de": "Baujahr", "en": "Year of Manufacture", "tr": "Üretim Yılı",
    },
    "ce.field_platform": {
        "de": "Steuerungsplattform (alt → neu)",
        "en": "Control Platform (old → new)",
        "tr": "Kontrol Platformu (eski → yeni)",
    },
    "ce.modification_desc": {
        "de": "Beschreibung der Veränderung",
        "en": "Description of the Modification",
        "tr": "Değişikliğin Tanımı",
    },
    "ce.modification_hint": {
        "de": "_(Vom Ingenieur auszufüllen: Umfang des Retrofits, getauschte "
              "Komponenten, geänderte Funktionen.)_",
        "en": "_(To be filled in by the engineer: scope of the retrofit, "
              "replaced components, changed functions.)_",
        "tr": "_(Mühendis dolduracak: retrofit kapsamı, değiştirilen "
              "bileşenler, değişen fonksiyonlar.)_",
    },
    "ce.questions_title": {
        "de": "Bewertungsfragen",
        "en": "Assessment Questions",
        "tr": "Değerlendirme Soruları",
    },
    "ce.q1": {
        "de": "Liegt eine Leistungserhöhung oder Funktionsänderung vor?",
        "en": "Is there a performance increase or functional change?",
        "tr": "Performans artışı veya fonksiyon değişikliği var mı?",
    },
    "ce.q1.hint": {
        "de": "z. B. höhere Taktzahl, neue Betriebsarten, geänderte "
              "Prozessführung",
        "en": "e.g. higher cycle rate, new operating modes, changed process "
              "control",
        "tr": "örn. daha yüksek çevrim, yeni işletme modları, değişen proses "
              "kontrolü",
    },
    "ce.q2": {
        "de": "Entsteht eine NEUE Gefährdung oder erhöht sich ein bestehendes "
              "Risiko?",
        "en": "Does a NEW hazard arise, or does an existing risk increase?",
        "tr": "YENİ bir tehlike doğuyor mu veya mevcut bir risk artıyor mu?",
    },
    "ce.q2.hint": {
        "de": "Risikobeurteilung der geänderten Teile heranziehen (RD05)",
        "en": "Use the risk assessment of the modified parts (RD05)",
        "tr": "Değiştirilen kısımların risk değerlendirmesini kullanın (RD05)",
    },
    "ce.q3": {
        "de": "Reichen die vorhandenen Schutzmaßnahmen weiterhin aus?",
        "en": "Are the existing protective measures still sufficient?",
        "tr": "Mevcut koruyucu önlemler hâlâ yeterli mi?",
    },
    "ce.q3.hint": {
        "de": "Wurden Schutzeinrichtungen verändert, entfernt oder umgangen?",
        "en": "Were protective devices modified, removed or bypassed?",
        "tr": "Koruyucu donanımlar değiştirildi, kaldırıldı veya atlandı mı?",
    },
    "ce.q4": {
        "de": "Falls nein: Kann der sichere Zustand mit EINFACHEN "
              "Schutzeinrichtungen wiederhergestellt werden?",
        "en": "If not: can the safe state be restored with SIMPLE protective "
              "devices?",
        "tr": "Hayırsa: güvenli durum BASİT koruyucu donanımlarla yeniden "
              "sağlanabilir mi?",
    },
    "ce.q4.hint": {
        "de": "einfach = ohne umfangreiche Eingriffe in die Steuerung "
              "(BMAS-Kriterium)",
        "en": "simple = without extensive intervention in the control system "
              "(BMAS criterion)",
        "tr": "basit = kontrol sistemine kapsamlı müdahale olmadan (BMAS "
              "kriteri)",
    },
    "ce.col_question": {
        "de": "Frage", "en": "Question", "tr": "Soru",
    },
    "ce.col_answer": {
        "de": "Antwort (Ja/Nein)", "en": "Answer (Yes/No)", "tr": "Yanıt (Evet/Hayır)",
    },
    "ce.col_notes": {
        "de": "Begründung / Nachweis", "en": "Rationale / Evidence", "tr": "Gerekçe / Kanıt",
    },
    "ce.result_title": {
        "de": "Ergebnis",
        "en": "Result",
        "tr": "Sonuç",
    },
    "ce.result_essential": {
        "de": "Wesentliche Veränderung: ☐ JA  ☐ NEIN — (vom Ingenieur "
              "anzukreuzen)",
        "en": "Essential modification: ☐ YES  ☐ NO — (to be ticked by the "
              "engineer)",
        "tr": "Esaslı değişiklik: ☐ EVET  ☐ HAYIR — (mühendis işaretleyecek)",
    },
    "ce.result_consequence_yes": {
        "de": "Bei JA: Die Maschine gilt als neue Maschine — vollständiges "
              "Konformitätsbewertungsverfahren (CE) erforderlich.",
        "en": "If YES: the machine counts as a new machine — a full conformity "
              "assessment procedure (CE) is required.",
        "tr": "EVET ise: makine yeni makine sayılır — tam uygunluk "
              "değerlendirme prosedürü (CE) gerekir.",
    },
    "ce.result_consequence_no": {
        "de": "Bei NEIN: Dokumentation dieser Bewertung aufbewahren; "
              "Betriebsanleitung und Risikobeurteilung aktualisieren.",
        "en": "If NO: retain this assessment documentation; update the "
              "operating manual and the risk assessment.",
        "tr": "HAYIR ise: bu değerlendirme dokümantasyonunu saklayın; kullanım "
              "kılavuzunu ve risk değerlendirmesini güncelleyin.",
    },
    "ce.rationale": {
        "de": "Gesamtbegründung",
        "en": "Overall Rationale",
        "tr": "Genel Gerekçe",
    },
    "ce.signature_engineer": {
        "de": "Verantwortlicher Ingenieur / fachkundige Person",
        "en": "Responsible Engineer / Competent Person",
        "tr": "Sorumlu Mühendis / Yetkin Kişi",
    },
    "ce.not_retrofit_warning": {
        "de": "Hinweis: Dieses Projekt ist nicht als Retrofit angelegt "
              "(project_type={ptype}) — die Bewertung „wesentliche "
              "Veränderung“ betrifft üblicherweise Bestandsmaschinen.",
        "en": "Note: this project is not set up as a retrofit "
              "(project_type={ptype}) — the essential-modification assessment "
              "usually applies to existing machines.",
        "tr": "Not: bu proje retrofit olarak tanımlı değil "
              "(project_type={ptype}) — esaslı değişiklik değerlendirmesi "
              "genellikle mevcut makineler içindir.",
    },

    # ── status / notice boxes ─────────────────────────────────────────────
    "status.pending": {
        "de": "AUSSTEHEND", "en": "PENDING", "tr": "BEKLEMEDE",
    },
    "status.pdf_failed": {
        "de": "PDF-Erstellung fehlgeschlagen — Markdown-Version wurde erzeugt.",
        "en": "PDF generation failed — the Markdown version was produced.",
        "tr": "PDF üretimi başarısız — Markdown sürümü üretildi.",
    },
}


# Convenience: structured FAT row bundles so generators don't re-assemble
# key names by hand (a typo would raise ProtocolI18nKeyError at run time,
# which the tests below catch — never an empty customer-document cell).

FAT_SAFETY_SCENARIOS = (
    "fat.safety.estop", "fat.safety.estop_release", "fat.safety.door_open",
    "fat.safety.reset_ok", "fat.safety.channel_mismatch", "fat.safety.maintenance",
)

FAT_SM_PREFIXES = tuple(f"fat.sm.t{i}" for i in range(1, 11))
FAT_STRESS_PREFIXES = tuple(f"fat.stress.t{i}" for i in range(1, 11))

SAT_CYBER_ROWS = (
    "sat.cyber.access_levels", "sat.cyber.default_pw", "sat.cyber.knowhow",
    "sat.cyber.ports", "sat.cyber.backup_tested", "sat.cyber.network_seg",
)
